#!/usr/bin/env bash
#
# Función que respalda el volumen que contiene la base de datos del SIAP.
# Ejemplo: ./back_up_my_volume

server_name="ciencia_datos@islasgeci.org"
source_data_volume_name="siap_mysql_vol"
backup_date=$(date +%F)
target_data_volume_name="${source_data_volume_name}_${backup_date}"

ssh ${server_name} \
  'docker run --rm --volume '${source_data_volume_name}':/from alpine ash -c "cd /from ; tar --create --file - . "' \
  | docker run --rm -i -v ${target_data_volume_name}:/to alpine ash -c "cd /to ; tar -xpvf - "
